#!/bin/bash

sudo docker rm riakcs > /dev/null 2>&1
	
RIAKCS=$(sudo docker run  -name riakcs -d -p 8000:8000 -p 8080:8080 -t internal_registry:5000/riak-cs)

echo "Started RIAKCS in container $RIAKCS"