FROM server:4444/base:latest

RUN add-apt-repository ppa:webupd8team/java
RUN apt-get update

# auto accept oracle jdk license
RUN echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
RUN apt-get install -y oracle-java7-installer
